### 1 - Import Library

In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report

### 2 - Load Dataset

In [2]:
df = pd.read_csv('wbc.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    str
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(1), str(1)
memory usage: 146.8 KB

In [4]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='str')

Variabel yang tidak digunakan :
- id
- Unnamed: 32

### 3 - Hapus variabel yang tidak digunakan

In [5]:
df = df.drop(columns=['id', 'Unnamed: 32'], errors='ignore')
X = df.drop(columns=['diagnosis'])
y = df['diagnosis']

### 4 - Pisahkan fitur dan target

In [6]:
X = df.drop(columns=['diagnosis'])
y = df['diagnosis']

### 5 - Encoding diagnosis

In [9]:
encoder = LabelEncoder()

y = encoder.fit_transform(y)

print(encoder.classes_)

[0 1]

### 6 - Pisahkan data training dan testing

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

### 7 - Buat Pipeline

In [11]:
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('selector', SelectKBest(score_func=f_classif, k=10)),
    ('model', LogisticRegression(max_iter=1000))
])

### 8 - Training Model

In [12]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('selector', SelectKBest()),
                ('model', LogisticRegression(max_iter=1000))])

In [13]:
y_pred = pipeline.predict(X_test)

### 9 - Evaluasi Model

In [14]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.956140350877193

In [15]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.99      0.97        72
           1       0.97      0.90      0.94        42

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114

### 10 - Cari jumlah fitur terbaik

In [16]:
results = []

for k in range(1, X.shape[1] + 1):

    pipeline = Pipeline([
        ('scaler', StandardScaler()),
        ('selector', SelectKBest(score_func=f_classif, k=k)),
        ('model', LogisticRegression(max_iter=1000))
    ])

    pipeline.fit(X_train, y_train)

    y_pred = pipeline.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)

    results.append({
        'k': k,
        'accuracy': accuracy
    })

results_df = pd.DataFrame(results)

results_df

     k  accuracy
0    1  0.929825
1    2  0.956140
2    3  0.956140
3    4  0.956140
4    5  0.964912
5    6  0.964912
6    7  0.964912
7    8  0.964912
8    9  0.973684
9   10  0.956140
10  11  0.973684
11  12  0.973684
12  13  0.973684
13  14  0.982456
14  15  0.973684
15  16  0.973684
16  17  0.973684
17  18  0.982456
18  19  0.982456
19  20  0.982456
20  21  0.973684
21  22  0.973684
22  23  0.973684
23  24  0.973684
24  25  0.973684
25  26  0.973684
26  27  0.973684
27  28  0.964912
28  29  0.964912
29  30  0.964912

In [18]:
# Cari yang terbaik
best_result = results_df.loc[results_df['accuracy'].idxmax()]

print("Jumlah fitur terbaik:", best_result['k'])
print("Accuracy:", best_result['accuracy'])

Jumlah fitur terbaik: 14.0
Accuracy: 0.9824561403508771

### 11 - Cari nama fitur terbaik

In [19]:
best_k = int(best_result['k'])

best_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('selector', SelectKBest(score_func=f_classif, k=best_k)),
    ('model', LogisticRegression(max_iter=1000))
])

best_pipeline.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('selector', SelectKBest(k=14)),
                ('model', LogisticRegression(max_iter=1000))])

In [20]:
# Ambil selector
selector = best_pipeline.named_steps['selector']

In [21]:
# Fitur terpilih
selected_features = X.columns[selector.get_support()]

print("Fitur yang dipilih:")
for feature in selected_features:
    print(feature)

Fitur yang dipilih:
radius_mean
perimeter_mean
area_mean
compactness_mean
concavity_mean
concave points_mean
radius_se
perimeter_se
radius_worst
perimeter_worst
area_worst
compactness_worst
concavity_worst
concave points_worst